### ISSUE TITLE
Claude and Gemini support

### ISSUE THREAD

**Issue by AndreaOrru** [bananaml/fructose#13]
As title.

**Comment by erik-dunteman** [comment]
We expect to break the main API as we figure out the exact abstractions, so won't be implementing other providers until it's clear people like the decorator + uses API of the current package.

Other than variety in the API quality, do Claude and Gemini offer API features that'd be useful for Fructose that OpenAI does not have?

**Comment by notune** [comment]
it would be nice if we could simply select another provider url, (or is this already possible)? for example with the openai package I can simply add another provider url, like openrouter, giving me access to lots of good&cheaper models:
```python
openrouter_client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=OPENROUTER_API_KEY,
)
```

**Comment by etiennebonnafoux** [comment]
Hello everyone,

Also could it support local LLM (Mistral or LaMMA)?

**Comment by notune** [comment]
> Hello everyone,
> 
> Also could it support local LLM (Mistral or LaMMA)?

if this project would add custom urls, then you would also be able to use local llm using ollama: https://github.com/ollama/ollama/blob/main/docs/openai.md

**Comment by notune** [comment]
I actually looked into the code, and it should actually already be possible. Just pass in a client when initializing fructose:
```
client = OpenAI(
  base_url="https://openrouter.ai/api/v1",
  api_key=OPENROUTER_API_KEY,
)
ai = Fructose(client=client)
```
