### ISSUE TITLE
Azure OpenAI

### ISSUE THREAD

**Issue by skhaz** [bananaml/fructose#14]
Is there any way to use the Azure API?

Thank you.

**Comment by erik-dunteman** [comment]
should be possible with using a custom client:
https://github.com/bananaml/fructose/issues/13#issuecomment-1984124960

though note that the @ai decorator uses the json return mode, and `uses` uses openai's tools, which have different behaviors or may not be supported on other providers. Assuming Azure OpenAI does support this full feature
