### ISSUE TITLE
Allow use as decorator without empty parens

### ISSUE THREAD

**Issue by jtratner** [bananaml/fructose#15]
If this is welcome, I'm down to help with this. (it's a really minimal change but might enhance the user experience)

Basically, with a little bit of pythonic sugar, you can allow for use both with and without parentheses:

For example, this:

```
@ai 
def myfunc(...):
   "whatever"
```

and also this:

```
@ai()
def myfunc2():
     pass

@ai(uses=[...])
def myfunc3():
     pass
```

Really just requires a couple lines of code in the `__call__` method, either changing signature to have keyword-only arguments:

```
def __call__(self, f=None, *, uses=...):
   # do all the same stuff
   if f:
      return decorator(f)
   else:
     return decorator
```

or adding a polymorphic check on uses:

```
def __call__(self, uses=...):
    potential_func = uses
    # do all the same stuff
    if callable(potential_func):
        return decorator(uses)
   else:
      return decorator
```

**Comment by erik-dunteman** [comment]
I agree, this is great and feels correct. Want to open a PR? Otherwise we'll get it added shortly

**Comment by erik-dunteman** [comment]
merged, will get new build pushed out now

**Comment by erik-dunteman** [comment]
now live in 0.0.11

**Comment by jtratner** [comment]
Awesome! (Sorry I didn't have time to check back but glad you were able to
implement it!)
